// Generated by gencpp from file restriction_point/test_srvRequest.msg
// DO NOT EDIT!


#ifndef RESTRICTION_POINT_MESSAGE_TEST_SRVREQUEST_H
#define RESTRICTION_POINT_MESSAGE_TEST_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace restriction_point
{
template <class ContainerAllocator>
struct test_srvRequest_
{
  typedef test_srvRequest_<ContainerAllocator> Type;

  test_srvRequest_()
    : pub(0)  {
    }
  test_srvRequest_(const ContainerAllocator& _alloc)
    : pub(0)  {
  (void)_alloc;
    }



   typedef int64_t _pub_type;
  _pub_type pub;





  typedef boost::shared_ptr< ::restriction_point::test_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::restriction_point::test_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct test_srvRequest_

typedef ::restriction_point::test_srvRequest_<std::allocator<void> > test_srvRequest;

typedef boost::shared_ptr< ::restriction_point::test_srvRequest > test_srvRequestPtr;
typedef boost::shared_ptr< ::restriction_point::test_srvRequest const> test_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::restriction_point::test_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::restriction_point::test_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::restriction_point::test_srvRequest_<ContainerAllocator1> & lhs, const ::restriction_point::test_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pub == rhs.pub;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::restriction_point::test_srvRequest_<ContainerAllocator1> & lhs, const ::restriction_point::test_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace restriction_point

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::restriction_point::test_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::restriction_point::test_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::restriction_point::test_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::restriction_point::test_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::restriction_point::test_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::restriction_point::test_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::restriction_point::test_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0938cb3886eca7912c33bd64ba079ab";
  }

  static const char* value(const ::restriction_point::test_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0938cb3886eca79ULL;
  static const uint64_t static_value2 = 0x12c33bd64ba079abULL;
};

template<class ContainerAllocator>
struct DataType< ::restriction_point::test_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "restriction_point/test_srvRequest";
  }

  static const char* value(const ::restriction_point::test_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::restriction_point::test_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 pub\n"
;
  }

  static const char* value(const ::restriction_point::test_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::restriction_point::test_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pub);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::restriction_point::test_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::restriction_point::test_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "pub: ";
    Printer<int64_t>::stream(s, indent + "  ", v.pub);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RESTRICTION_POINT_MESSAGE_TEST_SRVREQUEST_H
