// Generated by gencpp from file restriction_point/test_srv.msg
// DO NOT EDIT!


#ifndef RESTRICTION_POINT_MESSAGE_TEST_SRV_H
#define RESTRICTION_POINT_MESSAGE_TEST_SRV_H

#include <ros/service_traits.h>


#include <restriction_point/test_srvRequest.h>
#include <restriction_point/test_srvResponse.h>


namespace restriction_point
{

struct test_srv
{

typedef test_srvRequest Request;
typedef test_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test_srv
} // namespace restriction_point


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::restriction_point::test_srv > {
  static const char* value()
  {
    return "f0938cb3886eca7912c33bd64ba079ab";
  }

  static const char* value(const ::restriction_point::test_srv&) { return value(); }
};

template<>
struct DataType< ::restriction_point::test_srv > {
  static const char* value()
  {
    return "restriction_point/test_srv";
  }

  static const char* value(const ::restriction_point::test_srv&) { return value(); }
};


// service_traits::MD5Sum< ::restriction_point::test_srvRequest> should match
// service_traits::MD5Sum< ::restriction_point::test_srv >
template<>
struct MD5Sum< ::restriction_point::test_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::restriction_point::test_srv >::value();
  }
  static const char* value(const ::restriction_point::test_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::restriction_point::test_srvRequest> should match
// service_traits::DataType< ::restriction_point::test_srv >
template<>
struct DataType< ::restriction_point::test_srvRequest>
{
  static const char* value()
  {
    return DataType< ::restriction_point::test_srv >::value();
  }
  static const char* value(const ::restriction_point::test_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::restriction_point::test_srvResponse> should match
// service_traits::MD5Sum< ::restriction_point::test_srv >
template<>
struct MD5Sum< ::restriction_point::test_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::restriction_point::test_srv >::value();
  }
  static const char* value(const ::restriction_point::test_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::restriction_point::test_srvResponse> should match
// service_traits::DataType< ::restriction_point::test_srv >
template<>
struct DataType< ::restriction_point::test_srvResponse>
{
  static const char* value()
  {
    return DataType< ::restriction_point::test_srv >::value();
  }
  static const char* value(const ::restriction_point::test_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RESTRICTION_POINT_MESSAGE_TEST_SRV_H
